version: "3.9"

services:
  flask:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      - FLASK_ENV=development

  sqlite-web:
    image: coleifer/sqlite-web
    container_name: sqlite-web
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data:rw
    command: sqlite_web /data/app.db --host 0.0.0.0 --port 8080 --read-only